networkPolicies:
  enabled: true
  bundled:
    base:
      enabled: true
    conditional:
      enabled: true
    kubeApiAccess:
      enabled: false
      controlPlaneCidr:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    dynamic:
      enabled: true
      ssoCidr:
      - 0.0.0.0/0
  additionalPolicies: []